export type BusinessTag =
  | 'safe'
  | 'can-match-courier'
  | 'can-outsource'
  | 'motorcycle-only'
  | 'appjusto-only'
  | 'investor'
  | 'cultural-fit'
  | 'in-person-onboarding'
  | 'link-on-social'
  | 'ads'
  | 'consumer-home'
  | 'consumer-home-mousse'
  | 'consumer-home-vr'
  | 'dispatch-by-courier';
